name: build-and-deploy

on:
  push:
    branches:
      - main # Adjust to your default branch name

env:
  DOTNET_VERSION: 8.0.x
  BUILD_CONFIGURATION: Release
  PROJECT_PATH: ./ProductsApi    # Path to your project
  PUBLISH_PATH: ./myapp
  TESTRESULTS_PATH: ./test-results
  AZURE_WEBAPP_NAME: products-api # Your Azure Web App name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install Dependencies
        run: dotnet restore

      - name: Build Code
        run: |
          dotnet build \
            --configuration ${{ env.BUILD_CONFIGURATION }} \
            --no-restore

      - name: Run Unit Tests
        run: |
          dotnet test \
            --configuration ${{ env.BUILD_CONFIGURATION }} \
            --no-build \
            --logger trx \
            --results-directory ${{ env.TESTRESULTS_PATH }}

      - name: Store Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ${{ env.TESTRESULTS_PATH }}
        if: ${{ always() }}

      - name: Package Build
        run: |
          dotnet publish ${{ env.PROJECT_PATH }} \
            --configuration ${{ env.BUILD_CONFIGURATION }} \
            --no-build \
            --output ${{ env.PUBLISH_PATH }}

      - name: Store Build Artefact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ${{ env.PUBLISH_PATH }}

  deploy-test:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: ${{ env.PUBLISH_PATH }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.PUBLISH_PATH }}
